### ISSUE TITLE
Image URL not working?

### ISSUE THREAD

**Issue by odetecf** [DWilliames/Google-sheets-content-sync-sketch-plugin#21]
Works great and is exactly what I needed but when I add an image URL and try to load it into a shape it doesn't work (if I try to write it to a textbox the URL does appear as text though).

**Comment by junaid2ali** [comment]
It used to work for me with the older version of Sketch 51. With 52, it is also not working for me.

**Comment by junaid2ali** [comment]
Great thanks Kevin. I’ll try it out.

Sent from my iPhone

On Oct 19, 2018, at 11:27 AM, KevinMorais <notifications@github.com<mailto:notifications@github.com>> wrote:


I fixed the issue on my side, you can try this fork : https://github.com/KevinMorais/Google-sheets-content-sync-sketch-plugin

**Comment by odetecf** [comment]
Thanks for looking into it, but I'm afraid it still doesn't work for me :(

**Comment by droegier** [comment]
Same problem with Sketch 51 & 52 on MacOS 10.13.6

@KevinMorais's solution did not work for me. But I solved it myself in a similar way as him.

I basically replaced all `MSShapeGroup` by `MSRectangleShape` in the code.

**Comment by DWilliames** [comment]
Thanks all.
Sorry for the delay on this.

I just pushed a fix. :) #23 
Please let me know if it works now

**Comment by waltercoots** [comment]
I'm unsure if my issue's related, but I'm also unable to get the images to work. I wondered if it had to do with the URLs not being on https protocol, and only http. [Here's](https://docs.google.com/spreadsheets/d/1tPMByUYcEauVhspaef30OqlmWfjVzfaYyi05XJi9msE/edit#gid=0) the sheet I'm working with.

**Comment by jasonmcdermott** [comment]
I've found that http image urls don't work, only https @waltercoots

**Comment by waltercoots** [comment]
Good to know, thanks @jasonmcdermott!
